

initialNumberRecords: 1000
runCount: 4

logging:
  file: perftest.log
  level:
    ROOT: WARN
    org.springframework: ERROR
    com.millcreeksoftware: INFO

spring:
  data:
    mongodb:
      database: perftest
      host: localhost
      port: 27017

  datasource:
    url: jdbc:mysql://localhost:3306/perftest

  jpa:
    hibernate:
      ddl-auto: update
